server:
  port: 80
  servlet:
    context-path: /
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: true     #是否将自己注册进EurekaServer
    fetch-registry: true     #需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    name: cloud-order-service
