server:
  port: 8888
  servlet:
    context-path: /

spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /

  datasource:
    username: root
    password: 123456
    platform: h2
    url: jdbc:h2:file:E:\temp\shiro_demo;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

  #没密码 没设置
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 3000       # 连接超时时间 单位 ms（毫秒）
    pool:
      max-idle: 8       # 连接池中的最大空闲连接，默认值也是8
      min-idle: 0       # 连接池中的最小空闲连接，默认值也是0
      max-active: 8     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: -1      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出

logging:
  level:
    root: info
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

#redis
