
server:
  port: 8888
  servlet:
    context-path: /

spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /

  datasource:
    username: root
    password: 123456
    platform: h2
    url: jdbc:h2:file:E:\temp\shiro_demo;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    root: info
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

